config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # devise_for :models
  get 'welcome/index'

  root to: 'welcome#index'

  post "/recipes/:id/vote", to: "recipes#vote", as: "vote_recipe"
  resources :categories
  resources :recipes
  resources :ingredients
  resources :components

  # devise_scope :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  # end

  # get "/login", to: "sessions#new"
  # post "/login", to: "sessions#new"
  # delete "/logout", to: "sessions#destroy"
  get "/search", to: "recipes#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :difficulty_level, presence: true
  validates :rank, numericality: { only_integer: true }
  validates :name, uniqueness: true

  has_many :recipe_components, dependent: :destroy
  has_many :components, through: :recipe_components
  belongs_to :category


  def next_recipe
    Recipe.where("id > ?", id).order(:id).first
  end

  def previous_recipe
    Recipe.where("id < ?", id).order(:id).last
  end

  def capitalize_name
    self.name = self.name.capitalize
    self.save!
  end

  def self.search(q)
    Recipe.where("name like :query or description like :query", query: "%#{q}%")
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search, :vote]
  # skip_before_action :verify_authenticity_token, only: [:vote]

  def index
    @order = params[:order] || "name"
    @order_dir = params[:order_dir] || "asc"

    @recipes = Recipe.all.order(@order => @order_dir).paginate(page: params[:page], per_page: 10)
  end

  def new
    @recipe = Recipe.new
  end

  def create
   @recipe = Recipe.create(recipe_params)

   if @recipe.new_record?
    render "new"
   else
    redirect_to recipes_path
   end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @next_recipe = @recipe.next_recipe
    @previous_recipe = @recipe.previous_recipe
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to recipe_path
    else
      render "edit"
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path
  end

  def search
    @recipes = Recipe.search(params[:q])
    render :index
  end

  def vote
    recipe = Recipe.find(params[:id])
    if session[:voted_recipes_id].nil? || !session[:voted_recipes_id].include?(recipe.id)
      if params[:dir] == "up"
        recipe.increment!(:rank)
      elsif params[:dir] == "down"
        recipe.decrement!(:rank)
      end

      session[:voted_recipes_id] ||= []
      session[:voted_recipes_id] << recipe.id
      flash[:notice] = "Twój głos został zapisany!"
    else
      flash[:error] = "Już głosowałeś na ten przepis!"
    end

    redirect_to recipe_path(recipe)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :difficulty_level, :category_id)
  end
end

app/views/recipes/_form.html.erb
<%= render "common/errors", model: @recipe %>

<%= form_for(@recipe) do |f| %>
  <p>
    <%= f.label :nazwa %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :opis %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :poziom_trudności %><br>
    <%= f.number_field :difficulty_level, min: 1, max: 5 %>
  </p>

  <p>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </p>

  <p>
    <%= f.submit "Utwórz" %>
  </p>
<% end %>

<%= link_to "Wróć", categories_path,:class => 'btn btn-default' %>

app/views/recipes/_recipe.html.erb
<div>
 <p>
    <%= link_to recipe.name, recipe_path(recipe) %>
 </p>
</div>

app/views/recipes/edit.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h1>Edytuj przepis</h1>
</div>
<%= render :partial => 'form' %>

app/views/recipes/index.html.erb
<%- model_class = Recipe-%>
<div class="page-header">

<p>
  <%= form_tag "/search", method: "get" do %>
    <%= text_field_tag :q, params[:q], placeholder: "Szukaj..." %>
    <%= submit_tag "Szukaj" %>
  <% end %>
</p>

<h1>Przepisy:</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <!-- <th><%= model_class.human_attribute_name(:id) %></th> -->
      <th><%= link_to model_class.human_attribute_name(:nazwa), order_params("name", @order, @order_dir) %></th>
      <th><%= model_class.human_attribute_name(:opis) %></th>
      <th><%= model_class.human_attribute_name(:trudność) %></th>
      <th><%= link_to model_class.human_attribute_name(:polubienia), order_params("rank", @order, @order_dir, "desc") %></th>
      <!-- <th><%= model_class.human_attribute_name(:kategoria) %></th> -->
      <th><%= link_to model_class.human_attribute_name(:utworzono), order_params("created_at", @order, @order_dir) %></th>
      <th><%=  %></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <!-- <td><%= link_to recipe.id, recipe_path(recipe) %></td> -->
        <td><%= link_to recipe.name, recipe_path(recipe) %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.difficulty_level %></td>
        <td><%= recipe.rank %></td>
        <!-- <td><%= recipe.category_id %></td> -->
        <td><%=l recipe.created_at %></td>
        <td>

          <%= link_to "Edytuj",
                      edit_recipe_path(recipe), :class => 'btn btn-default btn-xs' %>
          <%= link_to "Usuń",
                      recipe_path(recipe),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Jesteś pewny?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @recipes, renderer: BootstrapPagination::Rails %>

<p>
  <%= link_to "Nowy przepis", new_recipe_path,
            :class => 'btn btn-primary' %> |
  <%= link_to "Wróć", categories_path,
            :class => 'btn btn-primary' %>
</p>

app/views/recipes/new.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h1>Nowy przepis</h1>
</div>
<%= render :partial => 'form' %>

app/views/recipes/show.html.erb
<%- model_class = Recipe -%>
<div class="page-header">
  <h1></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nazwa) %>:</strong></dt>
  <dd><%= @recipe.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:opis) %>:</strong></dt>
  <dd><%= @recipe.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:trudność) %>:</strong></dt>
  <dd><%= @recipe.difficulty_level %></dd>
  <dt><strong><%= model_class.human_attribute_name(:polubienia) %>:</strong></dt>
  <dd><%= @recipe.rank %></dd>
  <dt><strong><%= model_class.human_attribute_name(:kategoria) %>:</strong></dt>
  <dd><%= @recipe.category_id %></dd>
</dl>

<p>
  <strong>Rank:</strong>
  <%= link_to "-", vote_recipe_path(@recipe, dir: "down"), method: :post %>
  <%= link_to "+", vote_recipe_path(@recipe, dir: "up"), method: :post %>
</p>

<%= link_to  "Wróć", request.headers["Referer"] || recipes_path, :class => 'btn btn-default'  %>
<%= link_to  "Edytuj",
              edit_recipe_path(@recipe), :class => 'btn btn-default' %>
<%= link_to  "Usuń",
              recipe_path(@recipe),
              :method => 'delete',
              :data => { :confirm => "Jesteś pewny?" },
              :class => 'btn btn-danger' %>