config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # devise_for :models
  get 'welcome/index'

  root to: 'welcome#index'

  post "/recipes/:id/vote", to: "recipes#vote", as: "vote_recipe"
  resources :categories
  resources :recipes
  resources :ingredients
  resources :components

  # devise_scope :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  # end

  # get "/login", to: "sessions#new"
  # post "/login", to: "sessions#new"
  # delete "/logout", to: "sessions#destroy"
  get "/search", to: "recipes#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
  validates :name, uniqueness: true 

  has_many :recipes

  def capitalize_name
    self.name = self.name.capitalize
    self.save!
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)

    if @category.new_record?
      render "new"
    else
      redirect_to categories_path(@categories)
    end
  end

  def show
    @category = Category.find(params[:id])
    @recipe = Recipe.new
  end

  def index
    @categories = Category.all.order(name: :asc)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update

    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  def search
    @categories = Categories.search(params[:q])
    render :index
  end

  private

  def category_params
    params.require(:category).permit(:name, :text)
  end
end

app/views/categories/_category.html.erb
<div>
 <p>
    <%= link_to category.name, category_path(category) %>
 </p>                   
</div>

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => "form-horizontal category" } do |f| %>

  <% if @category.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nazwa, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Zatwerdź", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                categories_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1>Edytuj kategorię</h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1>Kategorie:</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <!-- <th><%= model_class.human_attribute_name(:id) %></th> -->
      <th><%= model_class.human_attribute_name(:nazwa) %></th>
      <!-- <th><%= model_class.human_attribute_name(:utworzono) %></th> -->
      <th><%= %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <!-- <td><%= link_to category.id, category_path(category) %></td> -->
        <td><%= link_to category.name, category_path(category) %></td>
        <!-- <td><%=l category.created_at %></td> -->
        <td>

          <%= link_to "Edytuj",
                      edit_category_path(category), :class => 'btn btn-default btn-xs' %>
          <%= link_to "Usuń",
                      category_path(category),
                      :method => :delete,
                      :data => { :confirm => "Jesteś pewny?" },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to "Nowy przepis", new_recipe_path,
            :class => 'btn btn-primary' %> |
  <%= link_to "Nowa kategoria", new_category_path,
            :class => 'btn btn-primary' %> |
  <%= link_to "Wróć", root_path,
      :class => 'btn btn-primary' %>
</p>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1>Kategoria</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nazwa) %>:</strong></dt>
  <dd><%= @category.name %></dd>
</dl>

<table class="table table-striped">

   <thead>
     <tr>
      <th><%= model_class.human_attribute_name(:nazwa) %></th>
      <th><%= model_class.human_attribute_name(:opis) %></th>
      <th><%= model_class.human_attribute_name(:trudność) %></th>
      <th><%= model_class.human_attribute_name(:polubienia) %></th>
      <!-- <th><%= model_class.human_attribute_name(:kategoria) %></th> -->
      <!-- <th><%= model_class.human_attribute_name(:utworzono) %></th> -->
      </th>
    </tr>
  </thead>

  <tbody>
    <% @category.recipes.each do |recipe| %>
      <tr>
        <td><%= link_to recipe.name, recipe_path(recipe) %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.difficulty_level %></td>
        <td><%= recipe.rank %></td>
        <!-- <td><%= recipe.category_id %></td> -->
        <!-- <td><%=l recipe.created_at %></td> -->
        <td>

      </td>
     </tr>
    <% end %>
   </tbody>
 </table>

<p>
  <%= link_to "Nowy przepis", new_recipe_path,
            :class => 'btn btn-primary' %> |
  <%= link_to  "Wróć",
               categories_path, :class => 'btn btn-default'  %>
  <%= link_to "Edytuj",
               edit_category_path(@category), :class => 'btn btn-default' %>
  <%= link_to "Usuń",
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</p>