config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # devise_for :models
  get 'welcome/index'

  root to: 'welcome#index'

  post "/recipes/:id/vote", to: "recipes#vote", as: "vote_recipe"
  resources :categories
  resources :recipes
  resources :ingredients
  resources :components

  # devise_scope :user do
  #   get 'sign_in', to: 'devise/sessions#new'
  # end

  # get "/login", to: "sessions#new"
  # post "/login", to: "sessions#new"
  # delete "/logout", to: "sessions#destroy"
  get "/search", to: "recipes#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:name) ? yield(:name) : "Kategorie" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
      <p>
         Hello <%= current_user.email %> |
         <%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %>
      </p>
      <% else %>
        <%= link_to "Zaloguj się", new_user_session_path %> |
        <%= link_to "Zarejestruj się", new_user_registration_path %>
      <% end %>

      <p style="color: green">
        <%= notice %>
      </p>

      <p style="color: red">
        <%= alert %>
      </p>

    <%= yield %>
  </body>
</html>

app/views/layouts/cook_book.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CookBook" %></title>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand", <%= link_to CookBook, root_path %></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <p>
            <!-- <%= link_to "Strona Domowa", root_path, :class => 'btn btn-primary' %> -->
            <% if current_user %>
              Witamy <%= current_user.email %> |
              <%= link_to "Wyloguj się", destroy_user_session_path, method: :delete, :class => 'btn btn-primary'  %>
            </p>
            <% else %>
            <%= link_to "Zaloguj się", new_user_session_path, :class => 'btn btn-primary'  %>
            <% end %>
            <!-- <li><%= link_to "Zarejestruj się", new_user_registration_path %></li> -->
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3></h3>
            <ul class="nav nav-list">
              <li class="nav-header"></li>
              <li><%= link_to "Kategorie", categories_path,:class => 'btn btn-primary'   %></li>
              <li><%= link_to "Przepisy", recipes_path, :class => 'btn btn-primary'   %></li>
              <li><%= link_to "Składniki", components_path, :class => 'btn btn-primary'  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>